### Imports

In [1]:
library(tidyverse)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.5.1
✔ ggplot2   4.0.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

### Datos

In [3]:
## Microdatos de la ENUT 2024
path = "/home/luisdx/Documents/dat4ccion/enut_2024_bd_csv/tsdem.csv"
TSDEM <- read.csv(path)
path = "/home/luisdx/Documents/dat4ccion/enut_2024_bd_csv/tmodulo.csv"
TMODULO <- read.csv(path)
path = "/home/luisdx/Documents/dat4ccion/enut_2024_bd_csv/tvar_crea.csv"
TVAR_CREA <- read.csv(path)

### Procesamiento: La Doble Jornada

In [4]:
codigos_hijos <- c(3, 4)
codigos_padres <- c(1,2)

df_aux_hijxs <- TSDEM %>%
  group_by(LLAVEHOG) %>%
  mutate(
    hogar_con_hijos = any(PAREN %in% codigos_hijos),
    TIENE_HIJOS = ifelse(hogar_con_hijos & PAREN %in% codigos_padres, 1, 0)
  ) %>%
  ungroup() %>%
  select(LLAVESDE, TIENE_HIJOS)

codigo_union <- c(1, 5)
df_aux_civil <- TMODULO %>%
  mutate(
    EST_CONY = ifelse(P4_5 %in% codigo_union, 1, 0)
  ) %>%
  select(LLAVEMOD, EST_CONY)

df <- TVAR_CREA %>%
  filter(EDAD >= 18) %>%
  left_join(df_aux_hijxs, by = c("LLAVEMOD" = "LLAVESDE")) %>% 
  left_join(df_aux_civil, by = "LLAVEMOD") %>% 
  mutate(
    GENERO = case_when(
      SEXO == 2 & ((TIENE_HIJOS == 1) | (EST_CONY == 1))  ~ "Mujer con pareja y/o descendencia",
      SEXO == 2 & !((TIENE_HIJOS == 1) | (EST_CONY == 1)) ~ "Mujer sin pareja ni descendencia",
      SEXO == 1 & ((TIENE_HIJOS == 1) | (EST_CONY == 1))  ~ "Hombre Unido y/o con Hij@s y/o con Niet@s",
      SEXO == 1 & !((TIENE_HIJOS == 1) | (EST_CONY == 1)) ~ "Hombre con pareja y/o descendencia",
      TRUE ~ NA_character_
    )
  ) %>%
  filter(!is.na(GENERO) & GENERO != "No especificado")

df$GENERACION <- cut(
  df$EDAD,
  breaks = c(-Inf, 30, 45, 60, Inf),
  labels = c("Menores de 30 años", "De 30 a 45 años", "De 45 a 60 años", "Mayores de 60 años"),
  right = FALSE
)
df$TRAB_NO_REM_TOTAL <- df$TRAB_NO_REM_HOG + df$TRAB_NO_REM_CON_CP

resumen <- df %>%
  group_by(GENERO, GENERACION) %>%
  summarise(
    Trabajo_Remunerado = weighted.mean(ACTIV_MERC, FAC_PER, na.rm = TRUE)/7,
    Trabajo_No_Remunerado = weighted.mean(TRAB_NO_REM_TOTAL, FAC_PER, na.rm = TRUE)/7,
    Tiempo_de_Ocio = weighted.mean(ACTIV_CONVIV, FAC_PER, na.rm = TRUE)/7, 
    Tiempo_de_Estudio = weighted.mean(ACTIV_ESTUD, FAC_PER, na.rm = TRUE)/7,  
    Tiempo_de_Autocuidado = weighted.mean(ACTIV_CUID_PER, FAC_PER, na.rm = TRUE)/7,
    Tiempo_Personal = weighted.mean(ACTIV_CONVIV+ACTIV_ESTUD+ACTIV_CUID_PER, FAC_PER, na.rm = TRUE)/7,
  ) %>%
  pivot_longer(cols = -c(GENERO, GENERACION), names_to = "TIEMPO", values_to = "HORAS")

`summarise()` has grouped output by 'GENERO'. You can override using the
`.groups` argument.

In [5]:
resumen

   GENERO                                    GENERACION
1  Hombre Unido y/o con Hij@s y/o con Niet@s Menores de 30 años
2  Hombre Unido y/o con Hij@s y/o con Niet@s Menores de 30 años
3  Hombre Unido y/o con Hij@s y/o con Niet@s Menores de 30 años
4  Hombre Unido y/o con Hij@s y/o con Niet@s Menores de 30 años
5  Hombre Unido y/o con Hij@s y/o con Niet@s Menores de 30 años
6  Hombre Unido y/o con Hij@s y/o con Niet@s Menores de 30 años
7  Hombre Unido y/o con Hij@s y/o con Niet@s De 30 a 45 años
8  Hombre Unido y/o con Hij@s y/o con Niet@s De 30 a 45 años
9  Hombre Unido y/o con Hij@s y/o con Niet@s De 30 a 45 años
10 Hombre Unido y/o con Hij@s y/o con Niet@s De 30 a 45 años
11 Hombre Unido y/o con Hij@s y/o con Niet@s De 30 a 45 años
12 Hombre Unido y/o con Hij@s y/o con Niet@s De 30 a 45 años
13 Hombre Unido y/o con Hij@s y/o con Niet@s De 45 a 60 años
14 Hombre Unido y/o con Hij@s y/o con Niet@s De 45 a 60 años
15 Hombre Unido y/o con Hij@s y/o con Niet@s De 45 a 60 años
16 Hombre Unido y/o con Hij@s y/o con Niet@s De 45 a 60 años
17 Hombre Unido y/o con Hij@s y/o con Niet@s De 45 a 60 años
18 Hombre Unido y/o con Hij@s y/o con Niet@s De 45 a 60 años
19 Hombre Unido y/o con Hij@s y/o con Niet@s Mayores de 60 años
20 Hombre Unido y/o con Hij@s y/o con Niet@s Mayores de 60 años
21 Hombre Unido y/o con Hij@s y/o con Niet@s Mayores de 60 años
22 Hombre Unido y/o con Hij@s y/o con Niet@s Mayores de 60 años
23 Hombre Unido y/o con Hij@s y/o con Niet@s Mayores de 60 años
24 Hombre Unido y/o con Hij@s y/o con Niet@s Mayores de 60 años
25 Hombre con pareja y/o descendencia        Menores de 30 años
26 Hombre con pareja y/o descendencia        Menores de 30 años
27 Hombre con pareja y/o descendencia        Menores de 30 años
28 Hombre con pareja y/o descendencia        Menores de 30 años
29 Hombre con pareja y/o descendencia        Menores de 30 años
30 Hombre con pareja y/o descendencia        Menores de 30 años
⋮  ⋮                                         ⋮
67 Mujer con pareja y/o descendencia         Mayores de 60 años
68 Mujer con pareja y/o descendencia         Mayores de 60 años
69 Mujer con pareja y/o descendencia         Mayores de 60 años
70 Mujer con pareja y/o descendencia         Mayores de 60 años
71 Mujer con pareja y/o descendencia         Mayores de 60 años
72 Mujer con pareja y/o descendencia         Mayores de 60 años
73 Mujer sin pareja ni descendencia          Menores de 30 años
74 Mujer sin pareja ni descendencia          Menores de 30 años
75 Mujer sin pareja ni descendencia          Menores de 30 años
76 Mujer sin pareja ni descendencia          Menores de 30 años
77 Mujer sin pareja ni descendencia          Menores de 30 años
78 Mujer sin pareja ni descendencia          Menores de 30 años
79 Mujer sin pareja ni descendencia          De 30 a 45 años
80 Mujer sin pareja ni descendencia          De 30 a 45 años
81 Mujer sin pareja ni descendencia          De 30 a 45 años
82 Mujer sin pareja ni descendencia          De 30 a 45 años
83 Mujer sin pareja ni descendencia          De 30 a 45 años
84 Mujer sin pareja ni descendencia          De 30 a 45 años
85 Mujer sin pareja ni descendencia          De 45 a 60 años
86 Mujer sin pareja ni descendencia          De 45 a 60 años
87 Mujer sin pareja ni descendencia          De 45 a 60 años
88 Mujer sin pareja ni descendencia          De 45 a 60 años
89 Mujer sin pareja ni descendencia          De 45 a 60 años
90 Mujer sin pareja ni descendencia          De 45 a 60 años
91 Mujer sin pareja ni descendencia          Mayores de 60 años
92 Mujer sin pareja ni descendencia          Mayores de 60 años
93 Mujer sin pareja ni descendencia          Mayores de 60 años
94 Mujer sin pareja ni descendencia          Mayores de 60 años
95 Mujer sin pareja ni descendencia          Mayores de 60 años
96 Mujer sin pareja ni descendencia          Mayores de 60 años
   TIEMPO                HORAS
1  Trabajo_Remunerado     7.790495771
2  Trabajo_No_Remunerado  4.115720956
3  Tiempo_de_Ocio         3.225646801
4  Tiempo_de_Estudio      0.119164464
5  Tiempo_de_Autocuidado  9.621450237
6  Tiempo_Personal       12.966261502
7  Trabajo_Remunerado     7.807943075
8  Trabajo_No_Remunerado  4.046326760
9  Tiempo_de_Ocio         2.995270508
10 Tiempo_de_Estudio      0.061628688
11 Tiempo_de_Autocuidado  9.432091182
12 Tiempo_Personal       12.488990379
13 Trabajo_Remunerado     7.201592552
14 Trabajo_No_Remunerado  2.652037590
15 Tiempo_de_Ocio         2.644219027
16 Tiempo_de_Estudio      0.022369755
17 Tiempo_de_Autocuidado  9.487839946
18 Tiempo_Personal       12.154428729
19 Trabajo_Remunerado     3.227204397
20 Trabajo_No_Remunerado  2.695893465
21 Tiempo_de_Ocio         2.959895835
22 Tiempo_de_Estudio      0.008390264
23 Tiempo_de_Autocuidado 10.170751745
24 Tiempo_Personal       13.139037845
25 Trabajo_Remunerado     5.228929615
26 Trabajo_No_Remunerado  2.249196015
27 Tiempo_de_Ocio         4.465619779
28 Tiempo_de_Estudio      1.728384230
29 Tiempo_de_Autocuidado  9.830838825
30 Tiempo_Personal       16.024842834
⋮  ⋮                     ⋮
67 Trabajo_Remunerado     1.18429891
68 Trabajo_No_Remunerado  5.60232042
69 Tiempo_de_Ocio         2.69255425
70 Tiempo_de_Estudio      0.01484767
71 Tiempo_de_Autocuidado 10.36492399
72 Tiempo_Personal       13.07232590
73 Trabajo_Remunerado     3.94107894
74 Trabajo_No_Remunerado  4.20018402
75 Tiempo_de_Ocio         4.28140103
76 Tiempo_de_Estudio      2.13852818
77 Tiempo_de_Autocuidado 10.17350062
78 Tiempo_Personal       16.59342983
79 Trabajo_Remunerado     5.60848490
80 Trabajo_No_Remunerado  5.35044960
81 Tiempo_de_Ocio         3.23490218
82 Tiempo_de_Estudio      0.19056670
83 Tiempo_de_Autocuidado  9.85641701
84 Tiempo_Personal       13.28188589
85 Trabajo_Remunerado     4.38882900
86 Trabajo_No_Remunerado  4.85610259
87 Tiempo_de_Ocio         2.75191559
88 Tiempo_de_Estudio      0.04565447
89 Tiempo_de_Autocuidado  9.90547546
90 Tiempo_Personal       12.70304553
91 Trabajo_Remunerado     1.14345808
92 Trabajo_No_Remunerado  3.59070576
93 Tiempo_de_Ocio         2.81301460
94 Tiempo_de_Estudio      0.02032365
95 Tiempo_de_Autocuidado 10.85448063
96 Tiempo_Personal       13.68781888

### Procesamiento: Brecha salarial desagregado por estado

In [ ]:
PATH <- "C:/Users/semiramis/Documents/Me/Dat4ccion/"
source(paste0(PATH, "/syntax/00-Inicio_Proyecto.R"))

library(tidyverse)
library(survey)

muestra_2024 <- readRDS(paste0(DATADIR, "muestra_2024.rds")) # 308598
muestra_inicial_2024 <- readRDS(paste0(DATADIR, "muestra_inicial_2024.rds")) # 135675

# unimos
vars_faltantes <- setdiff(names(muestra_2024), names(muestra_inicial_2024))

muestra_inicial_2024 <- muestra_inicial_2024 %>%   # 135675, 54
  left_join(
    muestra_2024 %>%
      select(id_persona, id_hogar, all_of(vars_faltantes)),
    by = c("id_persona", "id_hogar"))

# agrupacion nivel_edu
muestra_inicial_2024 <- muestra_inicial_2024 %>%
  mutate(
    nivel_edu = case_when(
      nivelaprob %in% c(0,1) ~ "Sin escolaridad / Preescolar",
      nivelaprob == 2 ~ "Primaria",
      nivelaprob == 3 ~ "Secundaria",
      nivelaprob %in% c(4,5,6) ~ "Media superior",
      nivelaprob %in% c(7) ~ "Superior",
      nivelaprob %in% c(8,9,10) ~ "Posgrado",
      TRUE ~ NA_character_))

muestra_inicial_2024$nivel_edu <- factor(
  muestra_inicial_2024$nivel_edu,
  levels = c(
    "Sin escolaridad / Preescolar",
    "Primaria",
    "Secundaria",
    "Media superior",
    "Superior",
    "Posgrado"))


# Diseño muestral
diseno <- svydesign(ids = ~1, data = muestra_inicial_2024, weights = ~factor)

# G1 — Scorecard: ingreso promedio ponderado por sexo
g1 <- svyby(~ingreso_mensual, ~sexo, diseno, svymean, na.rm = TRUE)
brecha <- (g1$ingreso_mensual[g1$sexo==2] /
             g1$ingreso_mensual[g1$sexo==1]) * 100

readr::write_csv(g1, paste0(OUTPUTDIR,"ENIGH_Brecha_ing_sex.csv"))

# G2 — Ingreso por nivel educativo y sexo
g2 <- svyby(~ingreso_mensual, ~sexo + nivel_edu, diseno, svymean, na.rm = TRUE)

g2$sexo <- factor(
  g2$sexo,
  levels = c(1,2),
  labels = c("Hombre","Mujer"))

### Procesamiento: Razón de Trabajo No Remunerado mujeres vs hombres desagregado por Estado

In [6]:
df <- TVAR_CREA %>%
  filter(EDAD >= 18) 
df$TRAB_NO_REM_TOTAL <- df$TRAB_NO_REM_HOG + df$TRAB_NO_REM_CON_CP
resumen <- df %>%
  group_by(SEXO, CVE_ENT) %>%
  summarise(
    TOTAL_TNR = weighted.mean(TRAB_NO_REM_TOTAL, FAC_PER, na.rm = TRUE)/7,
    .groups = "drop"
  ) 
resumen <- resumen %>%
  pivot_wider(
      names_from = SEXO,
      values_from = TOTAL_TNR,
    names_prefix = "SEXO_"
  ) %>%
  mutate(
    RATIO_TNR = SEXO_2 / SEXO_1
  )
cat_entidades <- data.frame(
  CVE_ENT_INT = 1:32,
  ESTADO = c("Aguascalientes", "Baja California", "Baja California Sur", "Campeche", 
             "Coahuila de Zaragoza", "Colima", "Chiapas", "Chihuahua", "Ciudad de México", 
             "Durango", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Estado de México", 
             "Michoacán de Ocampo", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", 
             "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", 
             "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz de Ignacio de la Llave", 
             "Yucatán", "Zacatecas"),
  ISO_CODE = c("MX-AGU", "MX-BCN", "MX-BCS", "MX-CAM", "MX-COA", "MX-COL", "MX-CHP", 
               "MX-CHH", "MX-CMX", "MX-DUR", "MX-GUA", "MX-GRO", "MX-HID", "MX-JAL", 
               "MX-MEX", "MX-MIC", "MX-MOR", "MX-NAY", "MX-NLE", "MX-OAX", "MX-PUE", 
               "MX-QUE", "MX-ROO", "MX-SLP", "MX-SIN", "MX-SON", "MX-TAB", "MX-TAM", 
               "MX-TLA", "MX-VER", "MX-YUC", "MX-ZAC")
)
resumen_final <- resumen %>%
  rename(CVE_ENT_INT = CVE_ENT) %>% 
  left_join(cat_entidades, by = "CVE_ENT_INT") %>%
  mutate(CVE_ENT_STR = str_pad(CVE_ENT_INT, width = 2, pad = "0"))
df_looker <- resumen_final %>%
  pivot_longer(
    cols = RATIO_TNR, 
    names_to = "KPI", 
    values_to = "VALOR_KPI"
  ) %>%
  select(CVE_ENT_INT, ESTADO, ISO_CODE, KPI, VALOR_KPI)

In [7]:
df_looker

   CVE_ENT_INT ESTADO                          ISO_CODE KPI       VALOR_KPI
1   1          Aguascalientes                  MX-AGU   RATIO_TNR 2.251906
2   2          Baja California                 MX-BCN   RATIO_TNR 1.799851
3   3          Baja California Sur             MX-BCS   RATIO_TNR 1.999925
4   4          Campeche                        MX-CAM   RATIO_TNR 2.282772
5   5          Coahuila de Zaragoza            MX-COA   RATIO_TNR 2.265615
6   6          Colima                          MX-COL   RATIO_TNR 2.175710
7   7          Chiapas                         MX-CHP   RATIO_TNR 2.706640
8   8          Chihuahua                       MX-CHH   RATIO_TNR 2.157134
9   9          Ciudad de México                MX-CMX   RATIO_TNR 1.903961
10 10          Durango                         MX-DUR   RATIO_TNR 2.263140
11 11          Guanajuato                      MX-GUA   RATIO_TNR 2.599985
12 12          Guerrero                        MX-GRO   RATIO_TNR 2.358819
13 13          Hidalgo                         MX-HID   RATIO_TNR 2.344462
14 14          Jalisco                         MX-JAL   RATIO_TNR 2.392337
15 15          Estado de México                MX-MEX   RATIO_TNR 2.420035
16 16          Michoacán de Ocampo             MX-MIC   RATIO_TNR 2.522692
17 17          Morelos                         MX-MOR   RATIO_TNR 2.446573
18 18          Nayarit                         MX-NAY   RATIO_TNR 2.479819
19 19          Nuevo León                      MX-NLE   RATIO_TNR 2.265683
20 20          Oaxaca                          MX-OAX   RATIO_TNR 2.614822
21 21          Puebla                          MX-PUE   RATIO_TNR 2.557576
22 22          Querétaro                       MX-QUE   RATIO_TNR 2.233761
23 23          Quintana Roo                    MX-ROO   RATIO_TNR 2.088073
24 24          San Luis Potosí                 MX-SLP   RATIO_TNR 2.391934
25 25          Sinaloa                         MX-SIN   RATIO_TNR 2.540187
26 26          Sonora                          MX-SON   RATIO_TNR 2.219139
27 27          Tabasco                         MX-TAB   RATIO_TNR 2.389607
28 28          Tamaulipas                      MX-TAM   RATIO_TNR 2.085961
29 29          Tlaxcala                        MX-TLA   RATIO_TNR 2.283227
30 30          Veracruz de Ignacio de la Llave MX-VER   RATIO_TNR 2.388601
31 31          Yucatán                         MX-YUC   RATIO_TNR 1.951000
32 32          Zacatecas                       MX-ZAC   RATIO_TNR 2.557171

### Procesamiento: Brecha Salarial Desagregado por Estado

In [2]:
path = "/home/luisdx/Documents/dat4ccion/enigh_2024_bv_csv/muestra_inicial_2024.csv"
MUESTRA <- read.csv(path)
MUESTRA$SEXO <- MUESTRA$sexo
MUESTRA$ENTIDAD <- MUESTRA$entidad
resumen <- MUESTRA %>%
  group_by(SEXO, ENTIDAD) %>%
  summarise(
    INGRESO_MENSUAL_ENTIDAD = weighted.mean(ingreso_mensual, factor, na.rm = TRUE),
    .groups = "drop"
  ) 
resumen <- resumen %>%
  pivot_wider(
      names_from = SEXO,
      values_from = INGRESO_MENSUAL_ENTIDAD,
    names_prefix = "SEXO_"
  ) %>%
  mutate(
    BRECHA_GEN = (SEXO_1 - SEXO_2) / SEXO_1
)
cat_entidades <- data.frame(
  CVE_ENT_INT = 1:32,
  ESTADO = c("Aguascalientes", "Baja California", "Baja California Sur", "Campeche", 
             "Coahuila de Zaragoza", "Colima", "Chiapas", "Chihuahua", "Ciudad de México", 
             "Durango", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Estado de México", 
             "Michoacán de Ocampo", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", 
             "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", 
             "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz de Ignacio de la Llave", 
             "Yucatán", "Zacatecas"),
  ISO_CODE = c("MX-AGU", "MX-BCN", "MX-BCS", "MX-CAM", "MX-COA", "MX-COL", "MX-CHP", 
               "MX-CHH", "MX-CMX", "MX-DUR", "MX-GUA", "MX-GRO", "MX-HID", "MX-JAL", 
               "MX-MEX", "MX-MIC", "MX-MOR", "MX-NAY", "MX-NLE", "MX-OAX", "MX-PUE", 
               "MX-QUE", "MX-ROO", "MX-SLP", "MX-SIN", "MX-SON", "MX-TAB", "MX-TAM", 
               "MX-TLA", "MX-VER", "MX-YUC", "MX-ZAC")
)
resumen_final <- resumen %>%
  rename(CVE_ENT_INT = ENTIDAD) %>% 
  left_join(cat_entidades, by = "CVE_ENT_INT") %>%
  mutate(CVE_ENT_STR = str_pad(CVE_ENT_INT, width = 2, pad = "0"))
df_looker <- resumen_final %>%
  pivot_longer(
    cols = BRECHA_GEN, 
    names_to = "KPI", 
    values_to = "VALOR_KPI"
  ) %>%
  select(CVE_ENT_INT, ESTADO, ISO_CODE, KPI, VALOR_KPI)

In [6]:
df_looker

   CVE_ENT_INT ESTADO                          ISO_CODE KPI        VALOR_KPI
1   1          Aguascalientes                  MX-AGU   BRECHA_GEN 0.2732940
2   2          Baja California                 MX-BCN   BRECHA_GEN 0.2615228
3   3          Baja California Sur             MX-BCS   BRECHA_GEN 0.2360659
4   4          Campeche                        MX-CAM   BRECHA_GEN 0.3452751
5   5          Coahuila de Zaragoza            MX-COA   BRECHA_GEN 0.3086182
6   6          Colima                          MX-COL   BRECHA_GEN 0.2752620
7   7          Chiapas                         MX-CHP   BRECHA_GEN 0.3393496
8   8          Chihuahua                       MX-CHH   BRECHA_GEN 0.2805027
9   9          Ciudad de México                MX-CMX   BRECHA_GEN 0.2384701
10 10          Durango                         MX-DUR   BRECHA_GEN 0.2590070
11 11          Guanajuato                      MX-GUA   BRECHA_GEN 0.2845192
12 12          Guerrero                        MX-GRO   BRECHA_GEN 0.2283022
13 13          Hidalgo                         MX-HID   BRECHA_GEN 0.3234917
14 14          Jalisco                         MX-JAL   BRECHA_GEN 0.3434537
15 15          Estado de México                MX-MEX   BRECHA_GEN 0.2686247
16 16          Michoacán de Ocampo             MX-MIC   BRECHA_GEN 0.4015281
17 17          Morelos                         MX-MOR   BRECHA_GEN 0.2627183
18 18          Nayarit                         MX-NAY   BRECHA_GEN 0.2641434
19 19          Nuevo León                      MX-NLE   BRECHA_GEN 0.3856787
20 20          Oaxaca                          MX-OAX   BRECHA_GEN 0.2808403
21 21          Puebla                          MX-PUE   BRECHA_GEN 0.2680543
22 22          Querétaro                       MX-QUE   BRECHA_GEN 0.2214264
23 23          Quintana Roo                    MX-ROO   BRECHA_GEN 0.2186524
24 24          San Luis Potosí                 MX-SLP   BRECHA_GEN 0.2181623
25 25          Sinaloa                         MX-SIN   BRECHA_GEN 0.2610090
26 26          Sonora                          MX-SON   BRECHA_GEN 0.2564868
27 27          Tabasco                         MX-TAB   BRECHA_GEN 0.3360606
28 28          Tamaulipas                      MX-TAM   BRECHA_GEN 0.2286732
29 29          Tlaxcala                        MX-TLA   BRECHA_GEN 0.2566582
30 30          Veracruz de Ignacio de la Llave MX-VER   BRECHA_GEN 0.2918493
31 31          Yucatán                         MX-YUC   BRECHA_GEN 0.2963490
32 32          Zacatecas                       MX-ZAC   BRECHA_GEN 0.3197365